[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "estregg-ybj"
version = "1.1.9"
description = "ESTREGG Space Exploration Terminal Game"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Jeorge Miclat", email = "corruption123ter@gmail.com" }
]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
windows = ["windows-curses; platform_system=='Windows'"]

[project.scripts]
estregg = "estregg.game:main"

[project.urls]
"Homepage" = "https://yb-jeorgie.github.io/estregg/"
"Repository" = "https://github.com/YB-Jeorgie/estregg-ybjj"
"Bug Tracker" = "https://github.com/YB-Jeorgie/estregg-ybj/issues"
